version: '3.8'

services:
  web:
    image: python:3.10-slim
    container_name: crawler
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - SCRAPY_SETTINGS_MODULE=crawlers.settings
      - PYTHONUNBUFFERED=1
    command: scrapy crawl batdongsan
